export default (data = {
  page: 1,
  total_results: 19817,
  total_pages: 991,
  results: [
    {
      vote_count: 495,
      id: 297802,
      video: false,
      vote_average: 6.9,
      title: "Aquaman",
      popularity: 568.65,
      poster_path: "/i2dF9UxOeb77CAJrOflj0RpqJRF.jpg",
      original_language: "en",
      original_title: "Aquaman",
      genre_ids: [28, 14, 878, 12],
      backdrop_path: "/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg",
      adult: false,
      overview:
        "Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis, and must step forward to lead his people and be a hero to the world.",
      release_date: "2018-12-07"
    },
    {
      vote_count: 78,
      id: 424783,
      video: false,
      vote_average: 6.4,
      title: "Bumblebee",
      popularity: 306.396,
      poster_path: "/sG6n4ei1F0kVQtTs3fAjDghngpa.jpg",
      original_language: "en",
      original_title: "Bumblebee",
      genre_ids: [28, 12, 878],
      backdrop_path: "/urPYbqQnMMu5Ug09nI0KAGabbDX.jpg",
      adult: false,
      overview:
        "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.  When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.",
      release_date: "2018-12-15"
    },
    {
      vote_count: 2278,
      id: 338952,
      video: false,
      vote_average: 7,
      title: "Fantastic Beasts: The Crimes of Grindelwald",
      popularity: 215.594,
      poster_path: "/kQKcbJ9uYkTQql2R8L4jTUz7l90.jpg",
      original_language: "en",
      original_title: "Fantastic Beasts: The Crimes of Grindelwald",
      genre_ids: [10751, 14, 12],
      backdrop_path: "/wDN3FIcQQ1HI7mz1OOKYHSQtaiE.jpg",
      adult: false,
      overview:
        "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
      release_date: "2018-11-14"
    },
    {
      vote_count: 32,
      id: 503314,
      video: false,
      vote_average: 7,
      title: "Dragon Ball Super: Broly",
      popularity: 212.105,
      poster_path: "/518jdIQHCZmYqIcNCaqbZuDRheV.jpg",
      original_language: "ja",
      original_title: "ドラゴンボール超（スーパー） ブロリー",
      genre_ids: [28, 16, 878],
      backdrop_path: "/6OTRuxpwUUGbmCX3MKP25dOmo59.jpg",
      adult: false,
      overview:
        "Earth is peaceful following the Tournament of Power. Realizing that the universes still hold many more strong people yet to see, Goku spends all his days training to reach even greater heights. Then one day, Goku and Vegeta are faced by a Saiyan called 'Broly' who they've never seen before. The Saiyans were supposed to have been almost completely wiped out in the destruction of Planet Vegeta, so what's this one doing on Earth? This encounter between the three Saiyans who have followed completely different destinies turns into a stupendous battle, with even Frieza (back from Hell) getting caught up in the mix.",
      release_date: "2018-12-14"
    },
    {
      vote_count: 3343,
      id: 335983,
      video: false,
      vote_average: 6.5,
      title: "Venom",
      popularity: 207.636,
      poster_path: "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
      original_language: "en",
      original_title: "Venom",
      genre_ids: [878],
      backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
      adult: false,
      overview:
        "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of an alien symbiote that gives him a violent super alter-ego: Venom. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
      release_date: "2018-10-03"
    },
    {
      vote_count: 240,
      id: 480530,
      video: false,
      vote_average: 6.6,
      title: "Creed II",
      popularity: 172.891,
      poster_path: "/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg",
      original_language: "en",
      original_title: "Creed II",
      genre_ids: [18, 28],
      backdrop_path: "/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg",
      adult: false,
      overview:
        "Follows Adonis Creed's life inside and outside of the ring as he deals with new found fame, issues with his family, and his continuing quest to become a champion.",
      release_date: "2018-11-20"
    },
    {
      vote_count: 224,
      id: 324857,
      video: false,
      vote_average: 8.7,
      title: "Spider-Man: Into the Spider-Verse",
      popularity: 161.501,
      poster_path: "/laMM4lpQSh5z6KIBPwWogkjzBVQ.jpg",
      original_language: "en",
      original_title: "Spider-Man: Into the Spider-Verse",
      genre_ids: [28, 12, 16, 878, 35],
      backdrop_path: "/e7CE5vx4KqUuz0peKdHRVZB0Pn8.jpg",
      adult: false,
      overview:
        'Miles Morales is juggling his life between being a high school student and being Spider-Man. However, when Wilson "Kingpin" Fisk uses a super collider, another Spider-Man from another dimension, Peter Parker, accidentally winds up in Miles\' dimension. As Peter trains Miles to become a better Spider-Man, they are soon joined by four other Spider-Men from across the "Spider-Verse". As all these clashing dimensions start to tear Brooklyn apart, Miles must help the others stop Fisk and return everyone to their own dimensions.',
      release_date: "2018-12-07"
    },
    {
      vote_count: 418,
      id: 463272,
      video: false,
      vote_average: 6.2,
      title: "Johnny English Strikes Again",
      popularity: 140.595,
      poster_path: "/tCBxnZwLiY1BOKw3tH6AxHZdqPh.jpg",
      original_language: "en",
      original_title: "Johnny English Strikes Again",
      genre_ids: [12, 10751, 28, 35],
      backdrop_path: "/b7Q0uX4Tcd6lXWItJEMxYk9XBbc.jpg",
      adult: false,
      overview:
        "Disaster strikes when a criminal mastermind reveals the identities of all active undercover agents in Britain. The secret service can now rely on only one man - Johnny English. Currently teaching at a minor prep school, Johnny springs back into action to find the mysterious hacker. For this mission to succeed, he’ll need all of his skills - what few he has - as the man with yesterday’s analogue methods faces off against tomorrow’s digital technology.",
      release_date: "2018-09-13"
    },
    {
      vote_count: 251,
      id: 428078,
      video: false,
      vote_average: 6.2,
      title: "Mortal Engines",
      popularity: 121.234,
      poster_path: "/uXJVpPXxZO4L8Rz3IG1Y8XvZJcg.jpg",
      original_language: "en",
      original_title: "Mortal Engines",
      genre_ids: [878, 28, 12],
      backdrop_path: "/rxYG6Sj95as9rv9wKIHUx6ATWd3.jpg",
      adult: false,
      overview:
        "Set in a world many thousands of years in the future. Earth’s cities now roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive Traction Cities, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the Outlands who will change the course of his life forever.",
      release_date: "2018-12-06"
    },
    {
      vote_count: 9998,
      id: 299536,
      video: false,
      vote_average: 8.3,
      title: "Avengers: Infinity War",
      popularity: 115.282,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      original_language: "en",
      original_title: "Avengers: Infinity War",
      genre_ids: [12, 28, 14],
      backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
      adult: false,
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      release_date: "2018-04-25"
    },
    {
      vote_count: 1213,
      id: 346910,
      video: false,
      vote_average: 5.2,
      title: "The Predator",
      popularity: 106.673,
      poster_path: "/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg",
      original_language: "en",
      original_title: "The Predator",
      genre_ids: [878, 28, 53, 12],
      backdrop_path: "/f4E0ocYeToEuXvczZv6QArrMDJ.jpg",
      adult: false,
      overview:
        "When a kid accidentally triggers the universe's most lethal hunters' return to Earth, only a ragtag crew of ex-soldiers and a disgruntled female scientist can prevent the end of the human race.",
      release_date: "2018-09-05"
    },
    {
      vote_count: 9,
      id: 507562,
      video: false,
      vote_average: 4.1,
      title: "Crayon Shin-chan: Burst Serving! Kung Fu Boys ~Ramen Rebellion~",
      popularity: 103.304,
      poster_path: "/fPc793wngYwFk1pziUNAoCCBmMU.jpg",
      original_language: "ja",
      original_title: "クレヨンしんちゃん 爆盛！カンフーボーイズ ～拉麺大乱～",
      genre_ids: [35, 12, 16],
      backdrop_path: "/oEu96CmVL9kjneOzjatLeeSZYS2.jpg",
      adult: false,
      overview:
        "Shin-chan is all set to challenge Kung Fu in the Chinatown of Kasukabe city, known as Aiyā Town.  He and the Kasukabe Defence Force are going to put up a totally no-stunt Kung Fu challenge on the stage.",
      release_date: "2018-04-13"
    },
    {
      vote_count: 599,
      id: 484247,
      video: false,
      vote_average: 6.4,
      title: "A Simple Favor",
      popularity: 88.612,
      poster_path: "/aIYsjQM0piKc0ibPBCTWv3sqshj.jpg",
      original_language: "en",
      original_title: "A Simple Favor",
      genre_ids: [53, 80, 9648, 35, 18],
      backdrop_path: "/xXGNyEG2v48q0bVR4AH4Vca2yvy.jpg",
      adult: false,
      overview:
        "Stephanie, a dedicated mother and popular vlogger, befriends Emily, a mysterious upper-class woman whose son Nicky attends the same school as Miles, Stephanie's son. When Emily asks her to pick Nicky up from school and then disappears, Emily undertakes an investigation that will dive deep into Emily's cloudy past.",
      release_date: "2018-08-29"
    },
    {
      vote_count: 161,
      id: 399402,
      video: false,
      vote_average: 5.7,
      title: "Hunter Killer",
      popularity: 86.137,
      poster_path: "/t7ZpEIxMnxaljIeor3XB1PUX4lm.jpg",
      original_language: "en",
      original_title: "Hunter Killer",
      genre_ids: [28, 53],
      backdrop_path: "/6li27rYziFeLlOjQh0oPN8ZRCZD.jpg",
      adult: false,
      overview:
        "An untested American submarine captain teams with U.S. Navy SEALs to rescue the Russian president, who has been kidnapped by a rogue general.",
      release_date: "2018-10-19"
    },
    {
      vote_count: 244,
      id: 426426,
      video: false,
      vote_average: 8.2,
      title: "Roma",
      popularity: 81.196,
      poster_path: "/dtIIyQyALk57ko5bjac7hi01YQ.jpg",
      original_language: "es",
      original_title: "Roma",
      genre_ids: [18],
      backdrop_path: "/uXs8rTXZDaWUclprxZuxfaZqei5.jpg",
      adult: false,
      overview:
        "In 1970s Mexico City, two domestic workers help a mother of four while her husband is away for an extended period of time.",
      release_date: "2018-08-25"
    },
    {
      vote_count: 2676,
      id: 353081,
      video: false,
      vote_average: 7.3,
      title: "Mission: Impossible - Fallout",
      popularity: 80.379,
      poster_path: "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
      original_language: "en",
      original_title: "Mission: Impossible - Fallout",
      genre_ids: [28, 53, 12],
      backdrop_path: "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg",
      adult: false,
      overview:
        "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
      release_date: "2018-07-13"
    },
    {
      vote_count: 2633,
      id: 424694,
      video: false,
      vote_average: 8.2,
      title: "Bohemian Rhapsody",
      popularity: 78.835,
      poster_path: "/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
      original_language: "en",
      original_title: "Bohemian Rhapsody",
      genre_ids: [18, 10402],
      backdrop_path: "/pbXgLEYh8rlG2Km5IGZPnhcnuSz.jpg",
      adult: false,
      overview:
        "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
      release_date: "2018-10-24"
    },
    {
      vote_count: 354,
      id: 454293,
      video: false,
      vote_average: 6.1,
      title: "Night School",
      popularity: 78.309,
      poster_path: "/xjsJTVWZYxeP89fwH17rsVvhPAe.jpg",
      original_language: "en",
      original_title: "Night School",
      genre_ids: [35],
      backdrop_path: "/eiUO8svuxMv16wvZsxubNLb5wNL.jpg",
      adult: false,
      overview:
        "Teddy Walker is a successful salesman whose life takes an unexpected turn when he accidentally blows up his place of employment. Forced to attend night school to get his GED, Teddy soon finds himself dealing with a group of misfit students, his former high school nemesis and a feisty teacher who doesn't think he's too bright.",
      release_date: "2018-09-27"
    },
    {
      vote_count: 1032,
      id: 369972,
      video: false,
      vote_average: 7.1,
      title: "First Man",
      popularity: 78.298,
      poster_path: "/i91mfvFcPPlaegcbOyjGgiWfZzh.jpg",
      original_language: "en",
      original_title: "First Man",
      genre_ids: [36, 18],
      backdrop_path: "/z1FkoHO7bz40S4JiptWHSYoPpxq.jpg",
      adult: false,
      overview:
        "A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon on July 20, 1969.",
      release_date: "2018-10-11"
    },
    {
      vote_count: 425,
      id: 407436,
      video: false,
      vote_average: 6.8,
      title: "Mowgli: Legend of the Jungle",
      popularity: 77.519,
      poster_path: "/clRnzMsFoMIdC7I5JsG6dnnHH8l.jpg",
      original_language: "en",
      original_title: "Mowgli: Legend of the Jungle",
      genre_ids: [12, 18],
      backdrop_path: "/2CECgwgaqfrkBigDe7ZadUhE2td.jpg",
      adult: false,
      overview:
        "A human child raised by wolves, must face off against a menacing tiger named Shere Khan, as well as his own origins.",
      release_date: "2018-11-25"
    }
  ]
});
